# Generated by Django 5.2.4 on 2025-08-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="invoice_id",
            field=models.CharField(
                default="INV1754138773.377024", max_length=20, unique=True
            ),
        ),
    ]
