# Generated by Django 5.2.4 on 2025-08-02 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0002_alter_sale_invoice_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("contact_person", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="drug",
            name="category",
            field=models.CharField(
                choices=[
                    ("Tablet", "Tablet"),
                    ("Syrup", "Syrup"),
                    ("Injection", "Injection"),
                ],
                default="Tablet",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="drug",
            name="manufacturing_date",
            field=models.DateField(default="2025-01-01"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sale",
            name="customer_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="prescription_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="sale",
            name="invoice_id",
            field=models.CharField(
                default="INV1754147194.412384", max_length=20, unique=True
            ),
        ),
        migrations.AddField(
            model_name="drug",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pos.supplier",
            ),
        ),
    ]
