# Generated by Django 5.2.4 on 2025-08-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0003_supplier_drug_category_drug_manufacturing_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="invoice_id",
            field=models.CharField(
                default="INV1754147516.171652", max_length=20, unique=True
            ),
        ),
    ]
